---
- hosts: all
  become: yes
  tasks:

  - name: copy timezone
    ansible.builtin.copy:
      src: /usr/share/zoneinfo/Europe/Moscow
      dest: /etc/localtime
      owner: root

  - name: restart chronyd
    ansible.builtin.systemd:
      name: chronyd
      state: restarted
      enabled: yes

  - name: update the rpm
    ansible.builtin.dnf:
      name:
        - rpm
      state: latest
      update_only: yes

  - name: install packages
    ansible.builtin.yum: name={{ item }} state=latest
    with_items:
      - traceroute
      - tcpdump
      - net-tools
      - nano
      - mc

- hosts: Servers
  become: yes
  tasks:

  - name: create ifcfg-vlan1
    ansible.builtin.template:
      src: ./files/ifcfg-vlan.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-vlan1
      owner: root
      group: root
      mode: 0644

  - name: restarted NetworkManager service
    ansible.builtin.systemd:
      name: NetworkManager
      state: restarted
      enabled: yes

- hosts: Clients
  become: yes
  tasks:

  - name: create ifcfg-vlan1
    ansible.builtin.template:
      src: ./files/ifcfg-vlan.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-vlan1
      owner: root
      group: root
      mode: 0644

  - name: restarted NetworkManager service
    ansible.builtin.systemd:
      name: NetworkManager
      state: restarted
      enabled: yes

- hosts: inetRouter,centralRouter
  become: yes
  tasks:

  - name: copy ifcfg-eth1 & ifcfg-eth1
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/sysconfig/network-scripts/
      owner: root
      group: root
      mode: 0644
    with_items:
      - ./files/ifcfg-eth1
      - ./files/ifcfg-eth2

  - name: create ifcfg-bond0
    ansible.builtin.template:
      src: ./files/ifcfg-bond0.j2
      dest: /etc/sysconfig/network-scripts/ifcfg-bond0
      owner: root
      group: root
      mode: 0644

  - name: restarted NetworkManager service
    ansible.builtin.systemd:
      name: NetworkManager
      state: restarted

  - name: Reboot the inetRouter & centralRouter
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible"
